version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "judimator"
    assignees:
      - "judimator"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "judimator"
    assignees:
      - "judimator"
